apiVersion: apps/v1
kind: Deployment
metadata:
  name: <deployment 이름>
  namespace: <namespace 이름>
  labels:
    <key> : <value>  # pod label
spec:
  replicas: <생성할 파드 수>
  selector:
    matchLabels:
      <key> : <value>  # pod label
  template:
    metadata:
      labels:
        <Pod Key> : <Pod Value> # pod label
    spec:
      nodeSelector:  # node label
        <Node key>: <Node Value>  
      serviceAccountName: <ServiceAccount 이름>
      containers:
        - name: <컨테이너 이름>
          image: <Docekr 이미지 경로>
          ports:
          - containerPort: <애플리케이션 포트>
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m

        # Fluent Bit sidecar 설정
        - name: fluent-bit
          image: fluent/fluent-bit:latest
          imagePullPolicy: Always
          env:
          - name: DD_API_KEY
            value: "<>"  # API KEY
          - name: DD_SITE
            value: "datadoghq.com"
          - name: DD_LOGS
            value: "true"
          - name: DD_SOURCE
            value: "kubernetes"
          - name: DD_DOCKER_LABELS_AS_TAGS
            value: '{"com.docker.compose.service":"service_name"}'
          ports:
          - containerPort: 2020
            name: metrics
          volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: config-volume
            mountPath: /fluent-bit/etc/
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: config-volume
          configMap:
            name: fluent-bit-config  # ConfigMap 이름
